project-icp/bee-pollinator-app

deployment/cfn/worker.py
src/mmw/js/src/analyze/tests.js

Connects #2 and #7 
At some point I made changes to the actual mmw repo instead of the bee pollinator and the patch file I made picked up some console log statements I had in for testing. This PR removes those.
Also removes `mounts` config for the deployment setup. Without RWD we don't need it anymore.

Fixup - Remove Console Logs From Tests + Mounts Config From Deployment Setup

---

src/icp/apps/modeling/tests.py
src/icp/js/src/compare/controllers.js
src/icp/js/src/compare/views.js
src/icp/js/src/modeling/controllers.js
src/icp/js/src/modeling/controls.js
src/icp/js/src/modeling/mocks.js
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/templates/controls/precipitation.html
src/icp/js/src/modeling/templates/controls/userInput.html
src/icp/js/src/modeling/tests.js
src/icp/sass/base/_header.scss
src/icp/sass/components/_buttons.scss
src/icp/sass/pages/_compare.scss

Bee pollinator model takes the number of managed hives as a numeric input, so this PR replaces the precipitation slider an number input field.
- Match the inverted dropdown button "Modifications" in the model header to the wireframes (ie make it blue)
- Set "New Scenario" as initial active tab
- Pull this branch
- `./scripts/bundle.sh`
- Draw a shape
- You should only be able to enter numeric values in the input field
- You should be able go to compare still
- There shouldn't be any errors in the console
Connects #30

Replace Precipitation Slider With Number Of Hives Input

---

src/icp/icp/settings/base.py
src/icp/icp/settings/production.py
src/icp/js/src/compare/views.js
src/icp/js/src/core/views.js
src/icp/js/src/modeling/views.js

During #12 we removed the template helpers of `ScenarioTabPanelView` - they set booleans we needed for the dropdowns on that view to appear. This PR adds the necessary template helpers back in.
Because it was such a quick fix and I had noticed what was causing the expand/collapse control to appear in the compare view (#39) I've also included a0feb80.
_Dropdown is back_
_Sidebar toggle no longer appears on compare maps_
- Pull this branch
- `./scripts/bundle.sh`
- Make sure the sidebar expand/collapse toggle still appears and works in the draw view
- Go to the model view and confirm the scenario dropdowns are there/working (they will not appear for "Current Conditions"
- Go to compare view and confirm there are no sidebar toggles on the little maps
Connects #33, #39

Fix Scenario Dropdowns and Compare View Map Sidebar Toggle

---

src/icp/js/src/core/views.js
src/icp/js/src/modeling/controllers.js
src/icp/js/src/modeling/views.js

This fixes an error that resulted in the UI being put into a bad state when app was backed out of the modelling view.
To test:
* clone this branch and bring up the environment
* navigate to `http://localhost:8000`
* draw an AoI and confirm it to move to the modelling view -->
* back out of this using the browser, and you should be returned to the same home view -->
* check the browser console for any errors; the `Failed to start modeling job.` and associated 500 error are expected
Connects #32

Fix UI error when transitioning from model view

---

src/icp/js/src/compare/controllers.js
src/icp/sass/pages/_compare.scss

We don't need to add the 100% Forest Cover scenario to the compare view, so now we only show the Current Conditions and whatever scenarios you've created.
It looked like each column should take up about half the screen if there were only 2 initial scenarios. Such wide columns made it hard to compare more than two scenarios at a time though, so I decided to only increase the column width a little. I think it'd be cool if they resized dynamically.
_Half viewport column widths_
- Pull this branch
- `./scripts/bundle.sh`
- Draw a shape and go to the compare view
- Confirm there are only 2 columns and no errors in the console
- Go back to Model, and add some more scenarios
- Check that the compare view still looks okay

Remove 100% Forest Cover From Compare View

---

src/icp/js/src/core/views.js
src/icp/js/src/modeling/controllers.js

"Current Conditions" are now the default scenario when a new project is created.
The area of interest now features a thin white border that makes it easier to differentiate, especially on satellite view.
Pull the branch, bundle the scripts.
Draw an area of interest. Switch to Satellite view. Ensure that the AoI is clearly distinguishable.
Proceed to the modeling view. Ensure that "Current Conditions" are active by default.
Connects #49 
Connects #50

Default to Current Conditions, Bordered AoI

---

src/icp/js/src/core/views.js

Adds currently active  basemap to compare view.
Check out the branch, bundle the scripts.
Open the app, draw an area of interest, proceed to the modeling, then the compare view. The maps in the compare view should have a satellite basemap.
Go back to the modeling view, and change the basemap to streets. Go forward to compare view. The maps in the compare view should have a street basemap.
Connects #67

Add Basemap to Compare View

---

src/icp/js/src/core/models.js
src/icp/js/src/core/utils.js
src/icp/js/src/draw/views.js
src/icp/js/src/geocode/templates/search.html

Switches displayed values to imperial rather than metric. I could not find any examples of length, thus didn't convert meters to feet. More values will come in to play as we flesh out the model side, so we'll have to keep this in mind.
Check out this branch, bundle scripts and hard refresh your browser.
* Notice the new message in the search bar in the home / draw views.
* Draw a very large area of interest (like half the country). The error message admonishing you should be in acres, not km².
* Draw a regular area of interest and move to the model view. Draw a modification for New Scenario. Click the modification. Its area should be displayed in acres.
* Click the modification dropdown in the top right of the model view. It should display the area of all drawn modifications in acres.
Are …

Display Imperial Units instead of Metric

---

src/icp/pollinator/src/pollinator/crop_yield.py
src/icp/pollinator/tests/tests.py

Computes the expected yield per cell based on algorithms provided by ICP Project members (see attached document).  Yield is a function of wild bee abundance and managed honeybee hive density, plus crop specific coefficients.
The output is also adjusted to report yield _per crop acre_ instead of per crop.  Since comparisons are made against yield types across scenarios where the specific amount of crop planted may change, we are converting the yield as calculated for a particular field to that of yield per acre of crop type on a particular field.  That way if the planted crop area is reduced, the yield per acre should be reduced in tandem, even if the change wasn't due to pollinator abundance.
Documentation: [Simple yield function for pollination …

Add yield calculation to pollinator model

---

src/icp/apps/modeling/tasks.py
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/tr55/runoff/views.js

Unlike MMW, land cover changes on the Current Conditions tab will carry over to the scenario tabs. Instead of running the model job for every open scenario, this PR sets up the model job to only kick off if: 
1) The scenario is current conditions (and it has no results/no resolved promise yet)
2) The scenario isn't current conditions, is active, and the current conditions job hasn't returned any results
3) There are new modifications
Otherwise we copy the current conditions results over to the initial "New Scenario", and don't rerun the model
Below you can see we're on a scenario tab with scenario results, but only the current condition tab has called the model (there's only one set of polling calls)
- Pull this branch and `./scripts/bundle.sh --debug`
- Open the Dev tools console
- Draw …

Use Current Condition Results In Scenarios Without Modifications

---

src/icp/js/src/compare/views.js
src/icp/js/src/core/modificationConfig.json
src/icp/js/src/core/templates/modificationPopup.html
src/icp/js/src/core/templates/sharedModificationPopup.html
src/icp/js/src/core/utils.js
src/icp/js/src/core/views.js
src/icp/js/src/modeling/controllers.js
src/icp/js/src/modeling/controls.js
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/modificationConfigUtils.js
src/icp/js/src/modeling/views.js

All modifications made or removed from the current conditions scenario are propagated across all other scenarios, including new and duplicated scenarios.  This facilitates using current conditions as a rectified base layer for constant model data. Both shared and scenario-specific modifications are submitted to the model endpoint. See detailed description in #87.
Additionally, the modification popups were altered to allow different behaviors for each type and the enhancement modifications were changed to types which have attributes more likely to affect the model output.
Connects #87 
There is a bug present on develop as well as this branch that cancels jobs too eagerly when switching between tabs if one is currently polling.  This can result in too many requests being generated for the …

Allow corrected land use to be applied to all scenarios

---

src/icp/js/src/core/overlayControl.js
src/icp/js/src/core/templates/overlayControl.html
src/icp/sass/components/_dropdowns.scss

Adds a legend for the crop layer, visible whenever the crop layer is visible. This is an initial stab. We need to replace "Crop n" labels with proper names, and better manage the number of items.
This uses placeholder colors. Actual colors are expected in #95 / #96. When the variables are updated, this should update automatically.
Pull down this branch. Run the bundle script. Open the app. Enable the crop layer. You should see a legend right above the crop layer button. It should go away when the crop layer is hidden.
Connects #74

Add Crop Layer Legend

---

src/icp/js/src/compare/controllers.js
src/icp/js/src/compare/templates/compareModeling.html
src/icp/js/src/compare/views.js
src/icp/js/src/core/chart.js
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/yield/views.js

This adds stacked bar charts to the Compare view, for the baseline and for each scenario.
For example, if the basic modelling view looks like this:
The Compare view now looks like this:
To test:
* clone this branch and open the app
* draw some AoI that has nonzero crop data somewhere within it and create at least one scenario with some set of modifications
* when the model has completed, open the "Compare" view and check that the stacked bar charts have been drawn and look accurate
Connects #94

Add yield results chart to Compare view

---

src/icp/js/src/core/models.js
src/icp/js/src/modeling/models.js

With the changes introduced for editing current conditions (CC), sharing modifications and the workflow that assumes the user will spend some time on CC, there were some inconsistent behavior introduced for when a scenario would poll for results, when that polling would be cancelled and when that polling would be diverted and just use an existing scenario's result. This PR adds additional guards to make sure that scenarios poll for results as expected
Connects #98 
Generally, adding modifications or changing inputs on any scenario should ultimately update that scenario, without interference from work on other scenarios. Some specifics to check:
* Multiple scenarios can be edited sequentially without waiting for polling to complete on any given one
* Switching tabs while scenarios are …

Consistent polling behavior

---

src/icp/js/src/core/chart.js
src/icp/js/src/modeling/yield/templates/table.html
src/icp/js/src/modeling/yield/templates/tableRow.html
src/icp/js/src/modeling/yield/views.js
src/icp/pollinator/src/pollinator/crop_yield.py
src/icp/pollinator/tests/tests.py
src/icp/sass/components/_charts.scss

Replace per acre yield with mean relative yield. Summing the yield values across a crop was a misuse of the yield value. It is more appropriate to simply average the crop yield cells and report that as the final crop yield value.  Reports out values on a 0-100 scale instead of 0-1.
Additionally updates charts to use 0-100 fixed scale and makes some small changes to
order and opacity between current conditions and the current scenario.
Connects #101 
Connects #102 
* Reprovision worker to install new model
* Check model tests pass
* Model results are returned as 0-100, and cannot be larger, even with high managed hive/acre counts
* Charts & Table are updated:
* Style is similar between compare and scenario
* CC comes first and is the lighter shade
* CC is darker shade on CC tab
* Output is …

Report output as average of relative crop yield

---

src/icp/js/src/compare/controllers.js
src/icp/js/src/compare/templates/compareModifications.html
src/icp/js/src/compare/views.js
src/icp/sass/pages/_compare.scss

Adds several new details to the compare view:
* Shared modifications in the mini-map
* Shared modifications in the list
* Number of Hives in the list
* Make better use of whitespace around table element, and increase the font size
Connects #106 
Height layout works well up to and including iPad Portrait layout, as it did previously.
* `vagrant provision worker` to ensure model is up to date
* `./scripts/bundle.sh --debug` to build static assets
* Create a project and verify the UI updates are as described.

Add additional information to compare view

---

README.md
src/icp/js/src/core/chart.js

In the analyze view, when the tooltip is displayed and new results arrived, a second tooltip appears. This PR fixes this problem by removing the tooltip when the chart is removed. This was first fixed in https://github.com/WikiWatershed/model-my-watershed/pull/1574.
* Go to the analyze view. 
* Make a modification.
* Hover over a bar in the bar chart so a tooltip appears.
* When the new results come back the tooltip should disappear. Moving the mouse should make a new tooltip appear.
Connects #109

Remove tooltip when chart is removed

---

src/icp/js/src/compare/controllers.js
src/icp/js/src/compare/templates/compareModeling.html
src/icp/js/src/compare/views.js
src/icp/js/src/core/chart.js
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/yield/views.js
src/icp/sass/components/_charts.scss

Adds an "All Crops" option to the compare chart, to view all crops with values in the AoI.  The chart is generally optimized for showing up to 4 crop types, which is the upper end of what actual users might have.  Things tend to get squished above that value, but the client thinks the vast majority will have only two crop types at a time.  Also, tries to simplify the compare chart by reusing the existing chart rendering code and not modifying the format of the `ResultsModel`.
Connects #107 
* Rebundle the front end assets `./scripts/bundle.sh --debug`
* Generate model results for a field that contains multiple crops
* In compare view, verify you can view all (up to 4) crops at once and still have the ability to choose single crop types.

Allow Compare All

---

src/icp/js/src/core/overlayControl.js
src/icp/js/src/core/templates/overlayControl.html
src/icp/sass/components/_buttons.scss
src/icp/sass/components/_dropdowns.scss

Makes the crop layer legend smaller and more manageable for small screens. It is now also toggle-able, thus can be turned off when not needed.
Connects #108 
On Windows (and probably Linux) systems, a vertical scrollbar will also be visible:
The original issue asked for potentially a hover-based solution. I didn't do that since it can lead to mistakes between moving the mouse from the overlay control to the legend, and scrolling within it. Hover based solutions are also inaccessible on touch devices.
Also tagging @jfrankl to get his feedback.
* Check out this branch, and run `bundle.sh` and go to [:8000/](http://localhost:8000/)
* Open the crop layer overlay control. Ensure the legend pops up as well, and is only one column instead of the previous four.
* Try scrolling the single column. …

Friendlier Crop Legend

---

src/icp/sass/components/_slider.scss

Connects #123 
This PR adds a transparent border to the opacity slider to make it easier to click. It also fixes the styling on IE11 which previously looked like this (it's missing entirely):
Pull and bundle
- Test that the opacity slider looks okay and is easy to click (ie has a large hit target) on Chrome, Firefox, IE11 and Safari

Increase opacity slider click area + IE11 fix

---

src/icp/js/src/modeling/controls.js
src/icp/js/src/modeling/templates/controls/userInput.html
src/icp/sass/base/_header.scss

Allows input for "number of hives" of single digit decimals, from 0 to 10.
Connects #124 
* Rebundle the client JS
* Attempt run the model with number of hives expressed as a decimal
* Verify that `/yield` requests include the decimal values
* Verify that the model output for two scenarios which share the same whole number, but different decimals, differ slightly.

Decimal hive inputs

---

deployment/ansible/services.yml

The `acl` package includes the setfacl tool, which Ansible 2.1+ uses to set POSIX ACLs to share modules with unprivileged users (`postgres` in this case).
See: http://docs.ansible.com/ansible/become.html
---
**Testing**
Provision the `services` virtual machine and ensure that it completes successfully.

Install ACL utilities to provision services VM

---

src/icp/pollinator/src/pollinator/data/cdl_data.csv
src/icp/pollinator/src/pollinator/data/cdl_data_grouped.csv
src/icp/pollinator/src/pollinator/reclass/group_cdl_data.py

Unifies a corrected "base" data set for the CDL.  This includes all actual CDL raster values, cover crop values and enhancement types, as well as Raspberries which were not included as a crop type in the CDL.  Attributes include managed hive `density` and HN/HF values.  Crops that are reported on with yield have density values, others do not need it.  Every crop needs HN/HF as they are part of the calculation for abundance, a precursor for yield.
The goal here is to condense the various client provided data into a single stream so that we don't have complex scripts that need to append segments simply because the data was delivered in chunks.  Future data changes from the client will have to come as modifications to this new `cdl_data.csv`
The group ids assigned here may be of value to …

Unify CDL data

---

src/icp/pollinator/src/pollinator/crop_yield.py

Updating the temporary demand values was overlooked when adding
additional crop types to the model in #140.  This caused the model to fail.
* Reinstall the model by either `vagrant provision worker` or `python setup.py install` on the vm
* Run a model and verify it executes correctly

Patch model demand for new group ids

---

src/icp/js/src/compare/controllers.js

Previously, we would create a sandboxed copy of the main project for the Compare view. This was done in order to preserve the state of the main project from any changes made in the Compare view, which could trigger model runs and modify input values.
This led to bugs such as spinners continuing to spin if that's how Compare view was initialized, even after any polling finishes. The original project's results would be updated, but not of the sandboxed copy, causing the user to see stale results.
Since we don't expect the Pollinator App to be able to trigger model runs from the Compare view, it is safe to remove the sandboxed copy of the project and just use the original one. This simplifies the code, making it easier to reason about, as well as removing any bugs like the one mentioned …

Use same project for Compare view as Modeling

---

src/icp/js/src/core/error/handlers.js
src/icp/js/src/core/modals/models.js
src/icp/js/src/core/modals/templates/alertModal.html
src/icp/js/src/core/modals/views.js
src/icp/js/src/core/views.js
src/icp/js/src/draw/views.js
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/tests.js
src/icp/js/src/modeling/views.js
src/icp/js/src/projects/views.js

Model only intended for fields of up to 400 acres, so the max size has been updated.
We were using `window.alert()` to show the error message, so I've ported over the MMW modals.
Connects #138 
* Pull this branch and bundle up
* Draw an AOI > ~5/8ths of a square mile
- should see error
* Draw good, little sized AOI, should succeed
* Rename scenarios to duplicate names/make stuff fail -- confirm there are no more `window.alert`

Max draw area size update  + fancy modals

---

deployment/packer/template.js

An updated version of the CDL raster was added to this snapshot and
will be associated with `icp-worker` instance types. 
Connects #155

Update CDL raster snapshot

---

src/icp/icp/settings/base.py
src/icp/icp/settings/production.py
src/icp/js/src/core/views.js

Makes sure that the basemap selector, overlay control and geolocation buttons are all consistently placed in both environments.  Previously, development had the layers but not the location and production had the location but not the layers.
Connects #158 
* Verify that development control show correctly
* Check production settings are updated to show the layer controls

Have consistent map controls in both development and production

---

src/icp/js/src/compare/utils.js
src/icp/js/src/compare/views.js
src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/views.js

Addresses various issues of the compare view resulting from loading it before all scenarios are done refreshing. Also does some minor refactoring of the fetch code.
See original issue for a detailed description (with animated GIFs) of the problems.
Connects #141
There is an interesting (good) side effect of the refactoring: when deleting modifications from a New Scenario so that it is identical to Current Conditions, it no longer polls for results, instead just copies the results from Current Conditions instantly.
When polling does finish in Compare view, all dropdowns will be reset to "All Crops" since a crop the dropdown may have been previously set to may no longer be available.
* Check out the branch and bundle your scripts `kj bundle --debug`
* Open the app and ensure you are not …

Always Compare Fresh Scenarios

---

src/icp/pollinator/src/pollinator/crop_yield.py
src/icp/pollinator/tests/tests.py

When `NODATA (0)` values are present in the CDL the model now assumes there is no yield for that cell. This scenario would be encountered when drawing an area on an a lake, or near a lake when the entire "beeshed" was taken into account.
The previous behavior was to generate an exception on trying to look up crop configuration based on the `NODATA` value.  A unit test has been added to verify this fix.
Connects #163 
* Install the updated model `vagrant ssh worker -c "cd /opt/app/pollinator && sudo python setup.py install"`
* Restart celery if needed, or `./scripts/debugcelery.sh`
* Search for Wildwood, Michigan and find the farm in the screenshot, just to the east of the geocoded point.  In fact, you can draw anywhere in that region that within ~2km of Lake Michigan (which contains the …

Account for NODATA values in yield calculation

---

src/icp/js/src/modeling/controls.js

If the user erases the value of Number of Hives, we take it to mean "Reset" and set the value to 0.
The first commit was an attempt to discard the empty value, and revert to the previous value, assuming the erasure was accidental. I'll squash it before merging.
Connects #166 
* Check out this branch and bundle scripts `./scripts/bundle.sh --debug`
* Get to the Modeling view, and erase the value of Number of Hives. Ensure that it updates to "0" when you leave the text box.
* Set the value to 2. Wait for the model run to finish. Then erase the value. Ensure that since the previous value was different, it triggers a model run.
* Erase the value again and leave the text box again. Ensure that since the previous value was 0, it does not trigger a model run.
* Ensure that setting values …

Set Number of Hives to 0 upon erasure

---

src/icp/pollinator/src/pollinator/crop_yield.py
src/icp/pollinator/src/pollinator/raster_ops/__init__.py
src/icp/pollinator/tests/tests.py

To help validate the model and share results, a method which can be
enabled manually has been added, which saves intermediate rasters to
disk.
Connects #205 
Using these saved rasters, I compared our output to that supplied by the ICP team.  At `2000m` buffer that we've been using, there is some noticeable misalignment of values, although they are distributed very similarly.  Increasing the buffer to `5000m` produced nearly identical results.  The comparison can be seen here: 
[Pollinator DST Model comparison.pdf](https://github.com/project-icp/bee-pollinator-app/files/971504/Pollinator.DST.Model.comparison.pdf)
Additionally, even though the farm abundance layer is created with differences at the two buffer values, there is a very marginal net change to the yield calculation output.
Crop …

Add debug output for rasters

---

src/icp/js/src/compare/templates/compareScenario.html
src/icp/sass/pages/_compare.scss

The compare view charts overlapped with the modeling info below them on short viewports:
If we move the modifications table down, it will be entirely off the screen on shorter viewports, so this PR just sets the entire compare column to scroll.
It also makes some styling updates per @jfrankl's suggestion: the spacing around the modification was unnecessarily large. I've also centered the "Navigate Scenarios" text on the back arrow.
Connects #179 
- Pull and `./scripts/bundle.sh` (make sure updated css files get written)
- Draw an AoI over somewhere with data (ie the triangle near `yuba city`)
- Go to "Compare"
- Confirm view is useable at a variety of window sizes

Fix compare view overlap on short viewports

---

src/icp/js/src/core/overlayControl.js
src/icp/js/src/core/templates/overlayControl.html

Render the CDL entries alphabetically by name.
Connects #209 
Giving Alfalfa the prominence it deserves:
* Bundle and ensure the legend order is alphabetical by name

Sort crop legend by legend name

---

src/icp/icp/settings/base.py

Switches the painted CDL over to the new one created as a result of #229 and locationtech/geotrellis#2170. 
- Pull this branch
- Switch the CDL layer on
- Zoom and pan around!
Connects #234

Update CDL Tile URL To Corrected Tiles

---

deployment/RELEASES.md
deployment/ansible/group_vars/all
deployment/ansible/roles/bee-pollinator.app/tasks/reverse-proxy.yml
deployment/ansible/roles/bee-pollinator.app/templates/nginx-app.conf.j2
src/icp/icp/settings/production.py

Ensure that pollinationmapper.org domains are used for all environments. Also, update the `DEFAULT_EMAIL_FROM` address so that the pollinationmapper.org domain is used.
Lastly, disable the unused Nginx OBSERVATION cache.
---
**Testing**
Navigate to the [new staging domain](https://staging.app.pollinationmapper.org/) and ensure that:
- The site works
- The certificate is valid
- The registration email comes from an pollinationmapper.org address

Update supported domains; remove unused Nginx cache

---

src/icp/bundle.sh
src/icp/js/src/compare/controllers.js
src/icp/js/src/compare/templates/compareModeling.html
src/icp/js/src/compare/templates/compareWindow.html
src/icp/js/src/compare/tours.js
src/icp/js/src/core/createTour.js
src/icp/js/src/core/templates/header.html
src/icp/js/src/core/templates/overlayControl.html
src/icp/js/src/modeling/controllers.js
src/icp/js/src/modeling/templates/controls/modDropdown.html
src/icp/js/src/modeling/templates/controls/userInput.html
src/icp/js/src/modeling/templates/scenarioTabPanel.html
src/icp/js/src/modeling/templates/scenariosBar.html
src/icp/js/src/modeling/templates/yieldScenarioToolbarTabContent.html
src/icp/js/src/modeling/tours.js
src/icp/js/src/modeling/views.js
src/icp/npm-shrinkwrap.json
src/icp/package.json
src/icp/sass/base/_tour.scss
src/icp/sass/main.scss

Add a tour to show new users around the model/compare stages of the app. 
We're using the tour library [hopscotch](http://linkedin.github.io/hopscotch/). It has its own API to handle state of seen/not seen using session storage, but it has several problems:
- it only expects to be managing a single tour, and the tour for this app has three stages: when you're on the current crop map tab, when you're on "new scenario" and when you're in the compare view. These three stages were best implemented using three separate tours
- it resets the state after a tour has ended so you can't tell if you've never seen a tour or if you've completed one
Because of this I've mostly ignored what hopscotch thinks the state is and wrapped each tour object in our own object that manages state via local storage …

Add new user tour

---

src/icp/js/src/modeling/models.js
src/icp/js/src/modeling/tests.js
src/icp/js/src/modeling/views.js
src/icp/sass/base/_header.scss

- add additional unit tests for renaming scenario behavior
- allow renaming to same name as the scenario already had
- disallow renaming to blank name
- allow double click on text to highlight
- start with all text highlighted
(This PR is basically identical to WikiWatershed/model-my-watershed#1683)
Connects #150 
- Rename scenarios confirming they begin highlighted, can be double clicked, and cannot be named another scenario's name or an empty string

Scenario rename behavior enhancements

---

src/icp/bundle.sh
src/icp/js/src/core/modals/templates/shareModal.html
src/icp/js/src/core/modals/views.js
src/icp/js/src/core/setup.js
src/icp/npm-shrinkwrap.json
src/icp/package.json

Flash-based clipboard access was recently removed from Chrome.  Consequently, copying the URL from the share dialogs was failing.  This switches to a JS based version that restores the previous functionality.
Implemented from work done in https://github.com/WikiWatershed/model-my-watershed/pull/2008 with caution around the subsequent findings on shrinkwrap.
Connects #248 
* Update your node_modules
* `rm -rf src/icp/node_modules` & `./scripts/npm.sh install`
* Rebundle both the app js and the vendor js
* Load the app, create a project, add a scenario, and save the project. Use the scenario menu to open the share dialog. Make the project public, and press the "Copy Link" button. Verify that the correct URL was added to the clipboard.
* Go through this process in multiple browsers

Replace ZeroClipboard with Clipboard

---

src/icp/js/src/core/templates/header.html
src/icp/js/src/core/templates/modificationPopup.html
src/icp/js/src/core/templates/sharedModificationPopup.html
src/icp/js/src/draw/templates/splash.html
src/icp/js/src/modeling/templates/yieldScenarioToolbarTabContent.html
src/icp/js/src/modeling/tours.js
src/icp/js/src/modeling/yield/templates/tableRow.html
src/icp/sass/pages/_compare.scss

Some small fixups requested by the client:
* Number are uniformly rounded to a single decimal place.
* Yuba Blue is used for output text color on compare
* "BETA" is added to the header branding.
* Updates helpguide link to new window & pollinationmapper.org
Connects #254 
Connects #225 
Connects #251 
Connects #249 
~~I matched the header style from the issue for the beta text, but also tried a version as a <sup>superscript</sup> as is common.  Looks like the following, we can do that if consensus indicates it looks better, I do.  I also did not add it to the tab title since we're not changing it to say "beta" every place within the app that it appears, let me know if you think otherwise.~~
*Update: we decided to user the superscript text as represented in Demo*
**Rounding and color** …

Small UI changes

---

src/icp/sass/base/_tour.scss

To ensure the tour is placed over all page elements, including the
Compare button, the z-index has been increased.  The value was chosen
as 1 larger than the Compare z-index, which was set to place _it_ over
the scenario drop down icon/menu.
Connects #270 
* After rebundling, clear your application data cache for the localhost site.  This will enable the tour.
* Advance to a project and cycle through the tour elements.  Ensure that there is no placement issue where the Compare button is over the bubble.

Increase z-index of tour bubble

---

src/icp/js/src/core/chart.js

When the number of crops is above 2 on compare, or 3 on the main
output, rotate the crop name slightly to avoid squished text. The
labels are not rotated under all circumstances because they look off
when there is plenty of room but are still rotated.
Connects #273

Rotate crop chart label to prevent crowding

---

deployment/cfn/data_plane.py

Define a custom ElastiCache parameter group with the `maxmemory-policy` set to `allkeys-lru`. This ensures that all keys (regardless of `expire set`) are evicted from the cache based on a LRU (less recently used) policy.
Also, update default PostgreSQL RDS engine version to 9.4.15.
Fixes https://github.com/project-icp/bee-pollinator-app/issues/280
---
**Testing**
I dumped the CloudFormation JSON produced by these changes and manually applied them to production. Login to the AWS Console and ensure that PostgreSQL RDS is at the correct version. Also, ensure that the parameter groups for the ElastiCache cache cluster has `allkeys-lru` set.

Add a custom ElastiCache parameter group with maxmemory-policy

---

Vagrantfile
deployment/ansible/group_vars/all
deployment/ansible/roles.yml
deployment/ansible/roles/bee-pollinator.base/meta/main.yml
deployment/packer/driver.py
deployment/packer/template.js
deployment/requirements.txt

This PR includes fixes for some of the inconsistencies I found when doing a Staging deployment. Changes are mostly version bumps and making sure dependencies are consistent across environments.
-  The `libpq` and `psycopg2` versions in `group_vars/all` were being overridden by hardcoded values in `bee-pollination.base/meta/main.yml`. As a result, the App servers are/have been using `psycopg2==2.6.*` and `libpq-dev=9.3.*`. According to https://github.com/project-icp/bee-pollinator-app/commit/5fe0b9500c7b9507d40c042bc325c831f5df4b95  that's the version that we _should_ be at, so I chose to use those versions instead of the newer ones in `group_vars/all`
- I deployed this project to Staging using Jenkins. See http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-develop/68/console …

Update deployment pipeline

---

README.md
Vagrantfile
deployment/ansible/group_vars/all
deployment/ansible/group_vars/development
deployment/ansible/group_vars/test
deployment/ansible/roles/bee-pollinator.base/defaults/main.yml
deployment/ansible/roles/bee-pollinator.beekeepers/tasks/main.yml
src/icp/apps/beekeepers/tasks.py
src/icp/apps/beekeepers/urls.py
src/icp/apps/beekeepers/views.py
src/icp/icp/urls.py
src/icp/requirements/base.txt

The beekeeper app will need to query rasters in s3 to get data at a point. The rasters are pre-processed by the client for single-value lookups and the data sets may be updated by the client directly on s3. This PR setups up beekeeper's first API endpoint with this functionality.
Connects #288 
Wow, AWS permissions were a serious doozy and delayed this PR significantly.
Rasterio making requests to s3 requires AWS IAM credentials. While boto3 under the hood of Rasterio automatically picks up various env variables pointing to or specifying AWS cred info, several manual steps by Ansible were necessary to make the AWS creds file readable from within Django by boto3.
- Correct `read` permissions on `~/.aws/` and its contents
- Mounting `~/.aws` to the correct user `$HOME` dir in the `app` VM …

Beekeeper raster endpoint

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx
src/icp/apps/beekeepers/js/src/reducers.js

The app user's map usage will be pretty simple -- if the user clicks the map, an apiary marker should be added. There should also be markers for all apiaries in the list. This PR adds that functionality.
Connects #300 
Follow up work:
- Map should handle double click zooms vs single clicks to add a marker
- Marker styling should be a circle matching its corresponding card
Click the map and see markers are added. Once a marker is added aka an apiary is added to the state's list of apiaries, the sidebar should change to the apiary card list. They are still dummy cards.
The `main` store also updates! You will need to add `main` to the store whitelist if you want to observe main persisting.

Map click adds marker to map and updates state

---

src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/package.json
src/icp/apps/beekeepers/sass/06_components/_map.scss
src/icp/apps/beekeepers/sass/main.scss
src/icp/apps/beekeepers/webpack.config.js
src/icp/apps/beekeepers/yarn.lock

The user should be able to search for a location on the map. This PR adds the ESRI geocoder, which is Civic Apps' standard geocoder choice. ESRI Geocoder will be helpful in the future when we have to reverse geocode apiary points for the default apiary name.
Connects #301 
I was digging kinda deep trying to clean this console issue. It doesn't break any app functionality. It is generated every time a geosearched address is selected and the map pans. I thought I'd get the PR up before I spent too much time spinning my wheel, when the non-breaking console error could be pinched off for the future or maybe someone is familiar with it.
Another known issue I'll add to #320 is that clicking the Geocoder sometimes (often) adds a marker underneath. The map clicking needs more finesse.
Use the …

Add ESRI geocoder to map

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/components/ScoresLabel.jsx
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/js/src/propTypes.js
src/icp/apps/beekeepers/js/src/reducers.js
src/icp/apps/beekeepers/views.py

The fetch endpoint for data already existed for a location/forage range/indicators. The front end has enough structure to request real data now instead of using mock dummy data. This PR hooks up the front and back ends officially and sets up the flow for when the database exists, authentication exists, and we save apiaries there.
I sketched this out as my train of thought. I can explain verbally if this doesn't make sense:
Connects #304 
- I based this branch off the Geocoder branch accidentally. I'll fix later or hopefully the other PR gets approved and merged first haha
- If you click outside PA, the requests loop infinitely because the front end doesn't know how to handle server errors from the fetch endpoint. I'll make a followup issue.
Click points within PA and try to use the …

Frontend fetches real data

---

src/icp/apps/beekeepers/migrations/0001_add_beekeepers_apiary_model.py
src/icp/apps/beekeepers/models.py

Django model and migration to add ORM model for Apiary features.
Connects #332 
* Check out branch and run migrations
`./scripts/manage.sh migrate`
* Interact with model in shell
```python
> ./scripts/manage.sh shell
from apps.beekeepers import models
from django.contrib.auth.models import User
user = User.objects.first()
bee = models.Apiary(
lat=34.34,
lng=-34.342,
marker="D",
name="Matt's Cool Apiary",
user=user
)
bee.save()
print(bee)
print(bee.id)
```
* Confirm apiary is persisted to DB
```shell
> ./scripts/manage.sh dbshell
select * from beekeepers_apiary;
```

Add Apiary Django model

---

src/icp/apps/beekeepers/migrations/0002_add_beekeepers_survey_model.py
src/icp/apps/beekeepers/models.py

Adds model for Survey.
Connects #334 
Includes an additional `surveytype` field not specified in the original card, since now we have to support more than one kind of survey: a long one and a short one, as discussed in [this document](https://docs.google.com/document/d/1WBEbPIAoex_kRQydom1420s_gBrEAk9Sh2sByYFHFjE/edit), the final details are still being worked out.
* Check out this branch and run `manage.sh migrate`
* Ensure the table is created appropriately

Add Beekeepers Survey Model

---

deployment/ansible/roles.yml
deployment/ansible/roles/bee-pollinator.app/meta/main.yml

During Ansible provisioning runs, the `Install NPM Dependencies` Beekeepers task occasionally causes the Node.js process to run out of memory. In an effort to allow this one-off process to have more memory to operate, a swapfile was added to boost virtual memory.
Fixes https://github.com/project-icp/bee-pollinator-app/issues/346
Review the contents of the following PR build logs:
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/205/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/206/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/208/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/209/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-p …

Add swapfile to application server

---

src/icp/apps/modeling/models.py
src/icp/apps/user/admin.py
src/icp/apps/user/migrations/0001_create_user_profile_model.py
src/icp/apps/user/migrations/0001_initial.py
src/icp/apps/user/migrations/0002_add_userprofiles_to_existing_users.py
src/icp/apps/user/models.py
src/icp/apps/user/views.py

The project already has Users for the Pollination Mapper app. Users from PM and Beekeepers will use the same User table, but we want to record from which app the User signed up. This PR adds a UserProfile attached to the User that can be extended to store other info (such as the future Beekeeper account profile).
This was done in place of moving to a custom `User` model. Django is protective of its User class and adding a custom User model would require copying all data to the new table (can't just add a new column to User). Since Bees is already in production, we want to preserve data / touch it as little as possible. We also gain flexibility to add user info later.
Connects #290
After creating a user via the Pollination Mapper sign up modal/workflow:
Apply migrations …

Record through which app User was created

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/sass/06_components/_card.scss
src/icp/apps/beekeepers/sass/06_components/_spinner.scss

Replace the TODO text in the apiary card with a spinner. The user sees the spinner when the data is fetching. I lifted the spinner CSS from MMW.
Connects #351 
FYI if you’re logged into the pollination front end, beekeepers requests to the backend will fail with a 403 due to CSRF protection. The underlying error: `CSRF Failed: CSRF token missing or incorrect.` It's ok for now, but we will want to fix that after login is implemented #327 . I've created #358
`./scripts/beekeepers.sh start`
Click on the map, and see the spinner go on the apiary card ~

Add spinner to apiary cards

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx
src/icp/apps/beekeepers/js/src/propTypes.js
src/icp/apps/beekeepers/migrations/0003_apiary_deleted.py
src/icp/apps/beekeepers/models.py
src/icp/apps/beekeepers/serializers.py
src/icp/apps/beekeepers/urls.py
src/icp/apps/beekeepers/views.py

- Users can list their own apiaries
- Users can create an apiary
- Users can retrieve an apiary
- Users can update an apiary
- Users can delete an apiary
When creating an Apiary, it should be given the following
arguments:
- lat, lng
- marker
- name
The following can be updated later:
- scores
- starred
- surveyed
The created Apiary is automatically associated with the User.
When users delete an Apiary, it is "soft-deleted". It will no longer be shown to the user, but will continue to exist in the database. A `deleted_at` field is introduced to record the time of soft deletion.
Front-end can upsert Apiaries in bulk at `/apiaries/upsert/` by POSTing an array of apiaries. If an apiary in the list has a matching ID, it will be updated, else inserted as a new apiary.
Connects #338 
~~At one …

Add /beekeepers/apiary/ endpoint

---

src/icp/apps/beekeepers/js/src/App.jsx
src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Header.jsx
src/icp/apps/beekeepers/js/src/components/LoginModal.jsx
src/icp/apps/beekeepers/js/src/components/ParticipateModal.jsx
src/icp/apps/beekeepers/js/src/components/SignUpModal.jsx
src/icp/apps/beekeepers/js/src/reducers.js
src/icp/apps/beekeepers/package.json
src/icp/apps/beekeepers/sass/06_components/_modal.scss
src/icp/apps/beekeepers/sass/06_components/_navbar.scss
src/icp/apps/beekeepers/webpack.config.js
src/icp/apps/beekeepers/yarn.lock

We've started working on the user management feature for Beekeepers as of #290 and this PR is the first of many for the UI. Set up the 3 types of auth modals and moving between them as per the wireframes, see issue for screen caps.
Note and pardon the `=` in the branch name, sloppy typing 😬 
Connects #325
The dispatched action from the modal closing is called twice, which is non-breaking and seems out of my control using the lib's close methods 🤔 -- reactjs-popup appears to be doing that. 
Unsure about my BEM implementation 😬 
Install the new npm lib with `./scripts/beekeepers.sh install`
`./scripts/beekeepers.sh start` 
Click "participate in study" in the top right and cycle through making sure things are as you expect. Some buttons that will eventually have functionality are set up to …

Implement modals for auth in the UI

---

src/icp/apps/beekeepers/js/src/components/Map.jsx

Adds an esri imagery basemap with a carto label-only overlay for context.  Limits the map zooming based on the availability of the overlays.
Connects #299 
Here's how it looks at different zoom levels:
The labels don't provide amazing contrast and are challenging to read over some types of land cover, however, out of what's available, this was the best I could produce.
* Ensure map layers are displayed

Add imagery basemap

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Header.jsx
src/icp/apps/beekeepers/js/src/components/LoginModal.jsx
src/icp/apps/beekeepers/js/src/csrfRequest.js
src/icp/apps/beekeepers/js/src/reducers.js
src/icp/apps/beekeepers/js/src/utils.js
src/icp/apps/beekeepers/sass/06_components/_modal.scss
src/icp/apps/user/views.py

This PR officially hooks up the beekeepers UI and Django user management. Users registered to either app will be able to sign in.
I added some basic error handling to show the user the error message from the server.
I had to loop in #358 to make a the POST request to `/user/login`. I spent a solid chunk of time solving it then realized GARP had to deal with the same issue, so I lifted that project's solution which is just `axios` set up to recognize available CSRF info.
Connects #358, #327
sucessfully logged in -->
As with the other actions fired by the modal's `close` method, clearing the auth error fires twice in most cases too.
I added a reducer set for storing user information. The fields we save are flexible. `username`, `userId`, and `authError` seemed like a good starting set.
My …

Implement logging in in Beekeepers UI

---

src/icp/apps/beekeepers/js/src/App.jsx
src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx

Wires up some of the front-end apiary activities with the back-end.
Connects #340 
* Log in. Refresh the screen. Ensure you are logged in.
* Make a few apiaries. Refresh the page. Ensure you see the same apiaries.
* Star some of them. Refresh the page. Ensure they're the same as before.
* Delete some of them. Refresh the page. Ensure they're still deleted.
* Inspect the database. Ensure the apiaries are still there, just with non-NULL values in `deleted_at`
* Log out by going to [:8000/user/logout](http://localhost:8000/user/logout), and then back to [:8000/?beekeepers](http://localhost:8000/?beekeepers)
* Ensure the making apiaries, starring, unstarring, and deleting work even when you're logged out

Wire Up Apiary Interaction with Back-end

---

README.md
scripts/make-vrts.sh
src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/ScoresLabel.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/tasks.py
src/icp/apps/beekeepers/views.py

Rasters are now provided as discrete files representing single states.
In order to mosaic them on the fly and read from the correct file, VRTs
have been created which reference adjacent raw geotiffs. Since rasterio
delegates vsis3 calls directly to gdal for the path, additional work
must be done to provide AWS credentials via environment variables as
rasterio will only continue to read the initial VRT read with it's own
configured credentials.
Connects #342 
VRTs and tifs together in a temporary s3 bucket:
Since other devs are currently using the tifs in the real staging bucket, I've created a temp bucket to hold these values until it's ready to be merged.  I'll then copy between buckets.  The bit of code around GDAL credentials was learned the hard way around previous work on USACE doing …

Update rasters for multi-state support

---

src/icp/apps/beekeepers/js/src/App.jsx
src/icp/apps/beekeepers/js/src/Survey.jsx
src/icp/apps/beekeepers/js/src/Surveys.jsx
src/icp/apps/beekeepers/js/src/components/Header.jsx
src/icp/apps/beekeepers/js/src/main.jsx
src/icp/apps/beekeepers/sass/06_components/_modal.scss
src/icp/apps/beekeepers/sass/06_components/_navbar.scss
src/icp/apps/home/urls.py

The survey view will live at its own route / page and this PR sets up the app to accomodate that future work.
Connects #329
The routes don't include the `?beekeepers` query param, which navigates correctly and eventually for staging/production when rather than check for that flag django routes to Beekeepers by the host path (whatever becomes the beekeepers domains). However, for development it is maybe a little annoying because if one refreshes the page they get rerouted to Pollination Mapper.
`./scripts/beekeepers.sh start` and navigate the tabs in the header
Routes at http://localhost:8000/survey/?beekeepers and http://localhost:8000/?beekeepers

Add survey route and navigation tabs

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx
src/icp/apps/beekeepers/js/src/utils.js

Initializes new apiaries with a reverse geocoded address for the point on which they were clicked, and a marker label which is next in the sequence. The marker is always one after the last Apairy's marker, in an Excel-style alphabetic sequence: A, B, ... Z, AA, AB, ... AZ, BA, ... ZZ, AAA, AAB, ...
Connects #370 
In some cases when the address is too long, it spills over into the next line. I'm leaving this until a design pass to fix. Will make a design pass card and highlight this there.
There is a slight flicker when adding a a new apiary on the map, as it is set once with a default name, then updated with the reverse geocoded name, then updated with the scores. I wasn't able to get to the bottom of this, but given 🚀🐦 I thought it was tolerable.
* Check out this branch and `beekeepers …

Initialize new Apiaries with Marker and Address

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/ApiaryMarker.jsx
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/utils.js
src/icp/apps/beekeepers/sass/06_components/_marker.scss

Adjusts the visual markers on the map to make them match the apiaries the correspond to and their state.
Connects #369 
The text on the map markers is slightly blurrier than on the sidebar. I believe this is because of the `transform3d` which is applied to all Leaflet elements. I don't think there is anything we can easily do about that.
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers) and add some apiaries
* Ensure they are added where you clicked them, that they match the marker of the apiary, and their color corresponds to the starred / surveyed state.

Match Marker to Sidebar Apiaries

---

src/icp/apps/beekeepers/js/src/components/EmptySurveyView.jsx
src/icp/apps/beekeepers/js/src/components/GuestSurveyView.jsx
src/icp/apps/beekeepers/js/src/components/Survey.jsx
src/icp/apps/beekeepers/js/src/components/SurveyView.jsx
src/icp/apps/beekeepers/sass/06_components/_survey.scss

Scaffold sections and states for the survey page. There are 3 states: not logged in; logged in, 0 apiaries; logged in, 1+ apiaries.
Connects #330
There's a flash of the 2nd scenario page if you log in with a user that has apiaries on the survey page. Not significant enough to address at the moment.
Hit http://localhost:8000/survey/?beekeepers at various stages of logged in/out and 0-1 apiaries.

Add landing pages for different survey tab states

---

src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCard.jsx
src/icp/apps/beekeepers/js/src/components/SurveyView.jsx
src/icp/apps/beekeepers/js/src/utils.js
src/icp/apps/beekeepers/sass/06_components/_survey.scss

Builds out the survey feature by sorting and displaying the survey cards. The only button or link that works is the "add to study" blue button. The rest go to root, for now.
There's basic styling, but there's much left to be desired. I've added some items to #393. I also didn't implement the map inset for time savings, I think the feature should be an enhancement instead #396 
Some assumptions were made about sorting and displaying data:
- Only month years between when the apiary was created and now will be avail for survey data collection
- Month years available to survey includes the current month (i.e. December-2018 as I write this PR)
- For April/Nov there is no specific check implemented for if a subsurvey for that month is Monthly or specialty April/Nov survey for that month. I …

Add survey cards and sort them correctly

---

src/icp/apps/beekeepers/js/src/App.jsx
src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/SignUpModal.jsx
src/icp/apps/beekeepers/js/src/utils.js
src/icp/apps/user/views.py

Expands the Sign Up dialog to have four entry fields for email, username, and two password fields. All fields are required, and HTML5 validation is used to ensure they are filled before sending it to the server.
Once complete, the data is sent to the `/user/sign_up?beekeepers` endpoint as form data, which returns validation errors or a success response. The first validation error is shown at the top of the dialog, using similar styling as in the Log In dialog. The query string is used to classify the new users as having signed up from the Beekeepers app,  as opposed to Pollination app.
If the sign up is successful, the Sign Up dialog is closed and the Log In dialog is opened, with a message prompting the user to click the activation link in their email. Once they have activated their …

Implement Sign Up workflow

---

deployment/ansible/roles/bee-pollinator.app/tasks/app.yml
deployment/ansible/roles/bee-pollinator.celery-worker/tasks/app.yml

A few files were converted to be symlinks in https://github.com/project-icp/bee-pollinator-app/commit/462882e1248198c0f630a877bd0e7b75bd8668d9. While this works for Vagrant, this broke for AMI builds. By adding `copy_links=yes` according to the [synchronize module](https://docs.ansible.com/ansible/latest/modules/synchronize_module.html), we ensure they are copied as the targets and not symlinks and work correctly.
Connects #404 
http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-app-and-worker/109/console
http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-staging-deployment/108/
The map legend (which relies on the symlinked files) is working correctly on staging:

Fix Build Failures by Copying Symlinks as Target Files

---

deployment/packer/template.js

The CDL tif has been updated to the 2017 version and placed on the
snapshot identified by the id added to our packer template.
Connects #407 
Connects #377 
I ran a scenario on the 2015 raster and another scenario on the 2017 version.  As you can see, one version had Cucurbits dropped between versions.
The 2017 CDL was reclassified according to the excellent notes in the readme.  The articaft, aside from being available on the snapshot volume, is in the publically available `icp-cdl-data`.  As the readme indicates, the 2017 prefixed version can be copied (sans prefix) to your host `/opt/icp-crop-data` directory in order to use/test it locally.  The other proportions remain largely the same.
* Update your local CDL version, as described in the Notes above.
* Confirm you can still run the …

Update the worker snapshot volume for 2017 CDL

---

src/icp/apps/beekeepers/.eslintrc
src/icp/apps/beekeepers/js/src/components/ApiarySurveyListing.jsx
src/icp/apps/beekeepers/js/src/components/Survey.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCard.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCardListing.jsx
src/icp/apps/beekeepers/js/src/components/SurveyView.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/js/src/propTypes.js
src/icp/apps/beekeepers/js/src/utils.js

Updates the Survey Listing for each apiary to list November, April, and Monthly surveys separately, with explicit marking. Pro users see all three kinds of listings, and Light users see only November and April listings. We begin counting from November 2018 for November and April surveys, and from the date of the apiary's creation for the Monthly surveys.
We still show the four most recent survey listings in a survey card, with the rest hidden behind a "View full history" button. Clicking that button opens a popup that lists all the surveys for that apiary.
Connects #398 
Connects #378 
For Pro Users:
For Light Users:
The Survey Detail dialog needs styling. I've made a note in #393.
* Go to …

List Surveys Based on User Contribution Level

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/sass/06_components/_card.scss
src/icp/apps/beekeepers/sass/06_components/_spinner.scss

The spinners when apiary cards loaded covered only the scores, and were displayed absolute to the page, not the card. Therefore, when the card list grew long and scrollable, spinners would float in space over the list.
This card fixes the spinners and fixes them over the entire card, not just the scores -- this has the benefit of not showing the apiary name until it is successfully reverse geocoded.
I gave cards a minimum height of 80px, which is roughly their height already when loaded with info.
Connects #392 
Click the map, add an apiary. Toggle the buffer. Add enough apiaries so the list scrolls. Spinners should act as you expect.

Overlap spinner to entire apiary card

---

src/icp/apps/beekeepers/js/src/components/LoginModal.jsx
src/icp/apps/beekeepers/js/src/components/ParticipateModal.jsx
src/icp/apps/beekeepers/js/src/components/ScoresLabel.jsx
src/icp/apps/beekeepers/js/src/components/SignUpModal.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/sass/06_components/_indicator.scss
src/icp/apps/beekeepers/sass/06_components/_modal.scss

To give a little more context to the apiary card content, scores will have popovers explaining the indicator and the score(s). The copy is yet to be provided.
Connects #372
I could have broken the popover content into its own functional component but the apiary cards are already really nested and I didn't think doing so would add clarity.
Run the project `./scripts/beekeepers.sh start`
Hover over an apiary card score

Add hover popups to scores

---

src/icp/apps/beekeepers/js/src/App.jsx
src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/SuccessModal.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCardListing.jsx
src/icp/apps/beekeepers/js/src/reducers.js

When the user survey submits successfully, the modal closes. It's unclear to the user that the survey submitted successfully, so we now flash a success modal for 2 seconds. We see the same modal when apiary surveys are submitted successfully.
I left the copy generic so the modal may be reused anywhere there's success.
~I looked into applying this same modal to the case of apiary Survey forms submitting successfully. Currently, they'll show the form in read-only mode with the submitted data. It's not perfect. The way the popup/modal is configured, closing the modal after a successful submit is not straightforward and would require passing down the close function from parent. I didn't see how to do this off the bat. So I'm leaving this as an enhancement.~ Literally a picky eslint formatting …

Flash success message modal after any survey succeeds

---

src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/icp/settings/base.py

Updates the app to use the new 2017 CDL raster for visualization. See https://github.com/project-icp/bee-pollinator-app/issues/371#issuecomment-456216003 for details.
Connects #371 
* Ensure the CDL layer loads and works correctly
* Also check the main app, ensure it loads the CDL layer correctly too

Use 2017 CDL Raster

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/ScoresLabel.jsx
src/icp/apps/beekeepers/js/src/constants.js

Splits the combined Floral scores into three top-level entries.
Connects #435 
This doesn't quite match the styling in the issue, because I imagine that's being worked on separately by @jfrankl.
* Check out this branch and `./scripts/beekeepers.sh start`
* Look at apiaries in the sidebar, ensure they match the new look proposed in the card

Split combined Floral scores into three top level scores

---

src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx

Previously, we did not clear out the state of the User Survey form when it was submitted. This led to previous values being reused if a user were to sign in to one account, fill out the survey, sign out, and sign in to another account, and fill it out again.
To prevent this from happening, we now clear the local state when the form is submitted.
Connects #409 
* Make sure you have two accounts that haven't filled out the User Survey. One way of doing this would be to delete two rows from the `beekeepers_usersurvey` table for the two accounts you're picking.
* Log in as the first account. Fill out the user survey. Make sure you specify a phone number.
* Log out. Log in as the second account. Ensure the user survey form is shown with initial values. Make sure the phone number field is …

Reset User Survey form state on submit

---

src/icp/apps/beekeepers/sass/06_components/_navbar.scss

Because we use the score labels as hover items, when a user hovers on them, the Popup library adds an inline style of `{ position: "relative" }` to the score label. This by default renders above the absolutely positioned user options dropdown. To fix this, we give the dropdown a small z-index.
Connects #438 
* Add a number of apiaries
* Scroll up, then hover over the user options dropdown. Ensure the options are not obscured.

Ensure user options are atop Survey Cards

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx

Previously, we would inadvertently sort the apiaries in place, causing their order in the redux state to be different. This interfered with the marker assignment for new apiaries, a function that assumes that the list in redux state is sorted by the default order.
Since changing the ordering of the redux state was inadvertent, this is now fixed by making a deep copy and sorting that when a non-default sort order is specified.
Also fixes a small issue where the Header component's prop type check would fail because `isStaff` was `undefined` for non-logged-in users.
Connects #437 
The third commit 69bab1e basically wipes out the first two, so they could've been dropped, but I've preserved them to show the process of thought.
* Add a few apiaries. Change the sort order …

Fix Apiary Add / Remove Behavior on Sort

---

src/icp/apps/home/views.py
src/icp/icp/settings/production.py

Add support for staging and production domains for the beekeepers app. The `?beekeepers` query string parameter is kept for local development.
Connects #432 
* Edit your `/etc/hosts` file (`$ sudo vim /etc/hosts`), and add this line at the very bottom:
127.0.0.1 app.beescape.org
* Add the following line to `base.py` (to allow this domain during development):
```diff
diff --git a/src/icp/icp/settings/base.py b/src/icp/icp/settings/base.py
index 5bbb8ceb..b4126c6d 100644
--- a/src/icp/icp/settings/base.py
+++ b/src/icp/icp/settings/base.py
@@ -208,6 +208,7 @@ SECRET_KEY = get_env_setting('DJANGO_SECRET_KEY')
ALLOWED_HOSTS = [
'.internal.azavea.com',
'localhost',
+    'app.beescape.org',
]
```
* Go to http://app.beescape.org:8000/ and ensure you see the beekeepers …

Update Settings for Domain Change

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx

Currently, if there is a server error while fetching apiary scores, they remain on screen and cannot be removed. By adding the same trash button to them that filled-in apiaries have, we allow the user two exits from the state: to retry and to remove the apiary.
Also, the apiary's marker is also added to the card, so the user can associate the malfunctioning API to the map.
Connects #453 
Also tagging @jfrankl 	for visual review.
The card asked for an ✖️ but I reused an existing component, and have the "trash" icon instead. I can change that if needed.
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers)
* Stop the server `vagrant ssh app -c 'sudo service icp-app stop'`
* Add an apiary. See the new failed UI.
* Ensure you can retry. …

Add ability to remove unfetched apiaries

---

src/icp/apps/beekeepers/js/src/components/EmptySurveyView.jsx
src/icp/apps/beekeepers/js/src/components/Header.jsx
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/components/ParticipateModal.jsx
src/icp/apps/beekeepers/js/src/components/Splash.jsx
src/icp/apps/beekeepers/js/src/components/SurveyView.jsx
src/icp/apps/beekeepers/js/src/components/Tooltip.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/sass/06_components/_icons.scss
src/icp/apps/beekeepers/sass/06_components/_modal.scss
src/icp/apps/beekeepers/sass/06_components/_tooltip.scss
src/icp/apps/beekeepers/templates/beekeepers/beekeepers.html
src/icp/apps/user/views.py
src/icp/templates/registration/activation_email.html
src/icp/templates/registration/activation_email.txt
src/icp/templates/registration/password_reset_email.html
src/icp/templates/registration/registration_base.html

The client provided copy to update around the app, which is full of lorem-ipsum placeholder text. This PR captures all requested changes to date with provided copy.
Connects #433 
The only really new thing are tooltips. They're pretty basic.
Still awaiting some text from client.
Most of the copy was copy & paste around the app.
Some of the changes are in email copy -- go through a sign up, activate your account, and resend activation link to make sure you see those changes in your console running `./scripts/debugserver.sh`. The check is not ideal but works I think -- the django templates only receive so much relevant info (I couldn't get a full path name to check for the `?beekeepers` querystring for example. If I missed something, lemme know).

Add copy to app

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/sass/06_components/_survey.scss

A lightweight change to ensure users don't submit incomplete forms, as they are uneditable after submission
Connects #445
Monthly:
In action:
This UI change is a UX compromise in light of the tight timeline and project constraints.
Pull down branch.
`./scripts/beekeepers.sh start`
Ensure that you cannot submit any apiary survey without checking the box.
Check that opening completed surveys is no problem, either. The confirmation checkbox should not show.

Add a confirm submission checkbox to all apiary surveys

---

Vagrantfile
src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/models.py

A flurry more of survey questions have tooltips now.
Connects #433
A subset of the changes.
Tooltips are not optimally placed on Firefox. You can probably tell which they are on the demo's above.
I changed of the project ports because of a conflict with another app, harkening back to my suggestion that it would be helpful to keep track of projects and ports for when we start new projects.
Pull down the PR and see tooltips across surveys.

Add tooltips to more survey questions

---

src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx

Previously, in the User Survey, Yes/No questions were presented as checkboxes. These are changed to be dropdowns, consistent with Apiary Surveys.
The final Confirmation checkbox for Apiary surveys is left as is.
Connects #466 
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers) and ensure you have a user without a User Survey
* Log in as that user.
- Ensure you see the User Survey.
- Ensure all the Yes/No questions are shown as dropdowns.
- Ensure they have the correct default values.
* Change some of them. Submit the form. Inspect the database.
- Ensure both Yes and No values are recorded correctly.

Make Yes/No questions a dropdown everywhere

---

deployment/ansible/group_vars/all

Without this we were getting:
```
vagrant@services:~$ sudo apt-get install 'redis-server=2:2.8.4-2'
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
redis-server : Depends: redis-tools (= 2:2.8.4-2) but 2:2.8.4-2ubuntu0.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```
See https://github.com/azavea/ansible-redis/issues/1
And …

Fix redis-server installation on services

---

deployment/ansible/group_vars/all
deployment/ansible/roles/bee-pollinator.beekeepers/tasks/main.yml

Docker CE `18.06.2` is incompatible with the Linux kernel `3.13`. Since Docker is easier to down/upgrade than the kernel version, downgrade Docker to `18.06.1` during provisioning, and uninstall Docker on AMI builds once we're done provisioning.
See:
* https://docs.docker.com/engine/release-notes/#18092
* https://github.com/docker/for-linux/issues/591
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736
Closes #473. 
* If you'd like to test the Docker deinstallation, adjust `deployment/ansible/roles/bee-pollinator.beekeepers/tasks/main.yml`:
```diff
--- a/deployment/ansible/roles/bee-pollinator.beekeepers/tasks/main.yml
+++ b/deployment/ansible/roles/bee-pollinator.beekeepers/tasks/main.yml
@@ -46,4 +46,4 @@
- name: Uninstall Docker
apt: pkg="{{ docker_package_name }}={{ …
```

Pin Docker to 18.06.1 during provisioning

---

deployment/ansible/roles/bee-pollinator.beekeepers/tasks/main.yml

While we would like to be able to remove Docker from the app AMI entirely as described in e104379a91abdb438bad70662aeefde936314d0e, the Docker Ansible role raises an error at the end of the AMI build if Docker is not installed (see: http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-app-and-worker/139/). Undo the Docker deinstall step during provisioning to get AMI builds passing again.
Closes #473.
* I'm not quite sure if there's an easy way to test an AMI build for a PR without clobbering the staging environment. If we can do that on Jenkins, I would recommend running a build to make sure this completes successfully.

Remove Docker deinstall from app provisioning

---

src/icp/apps/beekeepers/js/src/components/ScoresLabel.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/js/src/utils.js
src/icp/apps/beekeepers/sass/06_components/_indicator.scss

Adds score ranges, classification in the score popup.
This could potentially use some design input.
Connects #468 
Tagging @dboyer for visual review.
Need to confirm the Pesticide scores, which we are showing differently than their scale.
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers) and add some apiaries
* Hover over their scores.
- Ensure you see the table of expected results in the popup
- Ensure the scores and their classification is in line with the description in #468

Scores in Label Tooltips

---

src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx

The survey questions spreadsheet specifies questions that should appear conditionally based on answers to preceding questions. This PR should capture the rest of the questions that should be conditional but weren't yet. Questions  a user had second thoughts on and subsequently hides have their answers erased so we avoid saving stale / irrelevant data.
Connects #477 
**November:**
**User:**
Pull down branch and `./scripts/beekeepers.sh start`. Check out the user survey and november surveys. Try out the conditional questions. If you input answers but then change your mind on the parent input, the conditional question answers should be erased on change.

Update survey questions to be conditional where applicable

---

src/icp/apps/modeling/migrations/0021_clear_old_results.py
src/icp/js/src/modeling/models.js

Since we upgraded to the 2017 CDL in #410 and 598ed284, the current stored results in the database are out of date. By clearing them out, we ensure they will be recalculated when those scenarios are revisited.
Also fix issue with loading projects with their results cleared. In 1ddff11, as part of #165, the result fetching was refactored to be a little more eager. This works well for most cases, but when the results are artificially cleared, it would make existing projects crash, because the results would try to fetch before the project would finish loading (triggered by the project's fetch method), causing the front-end to request the yield without specifying an area of interest.
By adding a test to not fetch results until a project has loaded, we ensure that the eager call for project's …

Clear old Pollination Mapper results

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/GuestSurveyView.jsx
src/icp/apps/beekeepers/js/src/components/Header.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/models.py
src/icp/apps/beekeepers/sass/06_components/_navbar.scss

The app was tested by an elite group of beekeepers and these are the lower hanging fruit text changes.
Connects #486
I made a judgment call on the thymol and amitraz keys to turn the extra context into a tooltip, but I also want the descriptions I then wrote run by the client.
In the interest of saving time I didn't do the refactoring in forms that I would have otherwise liked 😢 
Make sure that all the surveys open and can submit successfully.
No typos.

Text changes for forms from beekeepers feedback

---

src/icp/apps/beekeepers/js/src/components/DropdownSelector.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/js/src/utils.js

This affects only the labels and not the inner variable definitions or S3 raster names. Thus, the upload instructions for the clients do not need to be updated.
Connects #488 
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers) and add an apiary
* Ensure the scores say "Insecticide" and "Insecticide load" instead of "Pesticide" or "Pesticide quality"

Rename Pesticide quality to Insecticide load

---

deployment/ansible/group_vars/all

The 9.4.* series of libpq-dev seems to have disappeared, so we
switch to 9.3. This is the only option here: https://packages.ubuntu.com/trusty/libpq-dev
This unblocks provisioning for `app` and `worker` VMs.
* Destroy and create `app` and `worker` and ensure they are created correctly

Downgrade to supported libpq-dev for Trusty

---

src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/SuccessModal.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCardListing.jsx
src/icp/apps/beekeepers/sass/01_settings/_type.scss
src/icp/apps/beekeepers/sass/05_base/_base.scss
src/icp/apps/beekeepers/sass/06_components/_modal.scss
src/icp/apps/beekeepers/sass/06_components/_survey.scss

Fixes the font loading issue in IE11, using ideas from [here](https://booking.design/implementing-system-fonts-on-booking-com-a-lesson-learned-bdc984df627f). We should consider flipping this sequence for all projects to ensure IE11 compatibility.
Also fixes tall modals in IE11 which were previously transparent below the window:
Also fixes the November Survey to load correctly in read-only mode. Previously some fields were not initialized correctly, and dropdowns were not disabled.
Connects #490 
Connects #465 
Fonts rendering correctly:
Modals scrolling correctly:
November Survey reinitializing correctly:
* Check out this branch and `beekeepers build`
* Test the site in IE11 (BrowserStack or Windows VM)
* Fill out a November Survey and save it. Make sure you pick non-default choices for …

Various IE11 Fixes

---

src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/ParticipateModal.jsx

Even though the front-end sends the apiaries to the back-end in the correct order, and they are saved in the correct order, for some reason when they are queried for again, the serializer sends them back in reverse order:
https://github.com/project-icp/bee-pollinator-app/blob/3ab3582d60da4eb8e4845ab15139e98b6a01ce90/src/icp/apps/beekeepers/serializers.py#L56-L64
https://github.com/project-icp/bee-pollinator-app/blob/3ab3582d60da4eb8e4845ab15139e98b6a01ce90/src/icp/apps/beekeepers/views.py#L161-L170
It was unclear how this can be remedied on the DRF side, as the documentation did not provide any hints, nor could this question be found on Stack Overflow.
In the interest of expediency, I've decided to sort the results in the front-end when the Monthly Survey details modal is loaded. This …

Show Monthly Survey Colonies in Correct Order

---

src/icp/apps/beekeepers/sass/06_components/_survey.scss
src/icp/apps/beekeepers/views.py

Fixes issues found during staging testing.
Previously this button was overlapping content:
That is now fixed:
---
Previously reloading the main app after logging in would fetch apiaries in a random order:
They are now always fetched in the correct order:
* Check out this branch and log in
* Make sure you have 0 apiaries. Delete all of them if needed.
* Go to the Survey page.
* Go to the Location finder.
* Add some apiaries. Delete one or two from the middle (not the first or the last).
* Refresh the page.

Fix Staging Issues

---

src/icp/apps/beekeepers/js/src/components/ApiarySurveyListing.jsx
src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCard.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCardListing.jsx
src/icp/apps/beekeepers/sass/06_components/_modal.scss

This improves the user experience by reminding the user the apiary for which they are filling out the details. Also includes some styling improvements to the "Full History" pop-up.
Connects #506 
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers)
* Go to the survey page and open different kinds of surveys
* Try opening the surveys from different places

Add Apiary Name to Survey Pop-ups

---

src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/migrations/0013_update_queen_source_options.py
src/icp/apps/beekeepers/models.py

Updates wording on a Varroa Management question, and adds a new Local Non-Commercial option to Queen Source.
Connects #507 
* On `develop` fill out a Monthly Survey
* Check out this branch and run migrations `manage migrate`
* Inspect the database
* Fill out a new Monthly Survey. Make sure to use "Local, non-commercial or reared on site" as the answer for "Where did the queen come from?"

Update Form Fields

---

src/icp/apps/beekeepers/views.py

Previously, we only exported the Survey tables. This was not enough, as the Apiary surveys could not be connected to the User surveys, since the user_id was never attached to the Apiary surveys.
By exporting the Apiary table along with the results, we give the entire set of collected data to the exporting user, which will give them the flexibility to connect and slice it in many different ways.
Furthermore, the user_id column is also added to the Survey table export, which can help make the connection without an extra step of connecting with an Apiary first.
Connects #505
* Log in with an admin account
* Export all data in zip file. Extract that file.

Add Apiary table to data export

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/CardButton.jsx
src/icp/apps/beekeepers/js/src/components/DropdownSelector.jsx
src/icp/apps/beekeepers/js/src/components/Sidebar.jsx
src/icp/apps/beekeepers/sass/06_components/_card.scss

Makes apiary names editable, as shown in the mockups.
Connects #303 
Tagging @jfrankl for visual review.
Some effort was made to make the input accessible via keyboard. This works for the most part, although it's probably not perfect. Given the 🚀🐦 nature of the project, this was all that could be done.
* Check out this branch and `update` and `server`
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers)
* Make a few apiaries
* Try editing their names
* Log in to an account. Try editing the apiary names now.

Editable Apiary Names

---

src/icp/apps/beekeepers/js/src/components/ApiarySurveyListing.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCard.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCardListing.jsx
src/icp/apps/beekeepers/js/src/propTypes.js
src/icp/apps/beekeepers/migrations/0014_update_hive_scale_id_help_text.py
src/icp/apps/beekeepers/models.py

Adds autofill using info from the most recent completed monthly survey.
Connects #463 
Completed surveys:
Autofilled surveys in id order:
There was an existing console warning about un/controlled inputs. There's a new console warning about requiring the `month_year` field on `lastMonthlySurvey` in some components that I haven't figured out how to clean up 🤔 
I rolled in #517
Start w a blank form
Connects #463, #517

Autofill select fields in monthly surveys

---

src/icp/apps/beekeepers/js/src/utils.js

The client requests monthly surveys be avail once the month begins. Currently, we allow the current month if it is past the 15th of the month (aka more than 1/2 of the month has passed)
Pull down branch, and run the project `./scripts/beekeepers.sh start`
http://localhost:8000/survey/?beekeepers and login
See that all surveys through June are still visible and you can successfully submit a June survey.

Include current month for monthly surveys

---

README.md
scripts/make-vrts.sh
src/icp/apps/beekeepers/js/src/components/Splash.jsx
src/icp/apps/beekeepers/js/src/constants.js

The client provided raster data for 5 new states, and updated PA, IL, and IN data too. This PR updates the VRT generation script. Also, I unified the code around the indicator label 'insecticide' formerly 'pesticide'. We had an in-between hybrid solution before to avoid renaming & regenerating data.
Connects #522
Data completes a full corridor between NY and MI :D
Data coming in from all included states, screenshot from my local instance
Staging:
I updated data in the staging data bucket in s3; staging will not return insecticide data until its code is updated to accomodate `insecticide`. Production will be a bit tricky. Either we upload the new VRTs and layers before the updated code is deployed, or after -- in both cases we'll get no data for the insecticide field for a few minutes. I …

Prepare app for 5 new states' raster data

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/migrations/0015_apiary_scores_nullify_data.py

The schema of the underlying scores data changed, thus invalidating the cached apiary scores. By wiping the scores, we allow a user to pull fresh data on next login. Said data is not automatically pulled because of budget constraints.
Connects #525 
Logged in with wiped data:
Pull down branch
Try to login and see that the app breaks
Apply the migration `./scripts/manage.sh migrate`
Refresh app and see the screenshot
Pull data and see that it comes back successfully

Add data migration to nullify scores

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/SurveyView.jsx
src/icp/apps/beekeepers/js/src/components/UserSurveyModal.jsx
src/icp/apps/beekeepers/js/src/propTypes.js
src/icp/apps/beekeepers/migrations/0016_add_notes_to_surveys.py
src/icp/apps/beekeepers/models.py
src/icp/apps/beekeepers/sass/06_components/_modal.scss
src/icp/apps/beekeepers/sass/06_components/_survey.scss

Performs minor changes requested by the user to all surveys. These are needed primarily for the Fall survey at this point, but have been applied to all surveys for uniformity (and because the clients have confirmed that they do want these changes on all surveys).
Connects #532 
Negative values are not allowed in numeric fields anymore:
Text changes to the Survey tab:
"Sell nucs/packages" in the User Survey:
Notes field on Monthly surveys:
Notes field on November surveys:
Notes field on April surveys:
* Run all migrations `$ ./scripts/manage.sh migrate`
* Run beekeepers `$ ./scripts/beekeepers.sh start`
* Sign up as a new user to see the User Survey
* Go to the Surveys tab
* Open different kinds of Apiary surveys to verify the Notes field
* On the different kinds of …

Minor Changes to Surveys

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/constants.js

The question "What do you think was the most likely cause of colony loss?" suggests that there was colony loss. It is possible there wasn't, and so add an answer option that indicates as such.
This change was tucked away in the client's wires and got missed in #533 
Connects #542 
Pull down the branch. If your haven't pulled down develop in the last few days, make sure to run migrations and possibly `./scripts/beekeepers.sh install`. Though, there were no added migrations or yarn dependencies here.
`./scripts/beekeepers.sh start`

Add an 'n/a' option to a spring survey question

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/utils.js

Fix geocoder searches panning & zooming the map. This bug was introduced by formatting coordinate information as an array instead of an object 😱 
Also, I removed the beekeepers prototype because we don't need that anymore and it's generating dependabot PRs.
Refs #548 
Use the geocoder and see that selecting a location pans & zooms the map as many times as you select new locations.
See no weird behavior clicking apiary card markers to pan & zoom to their locations.

Bugfix: unify on map center format

---

src/icp/apps/beekeepers/js/src/components/ApiaryCard.jsx
src/icp/apps/beekeepers/js/src/components/CardButton.jsx

Users had trouble interpreting the image buttons for edit and save
within the card component, so we replaced the icons with text to clarify
their purpose. Refactored the CardButton component export into two
higher-order components, CardButtonWithText and CardButtonWithIcon, to
allow reusability of the CardButton code as well as differing sets of
required props for the different button types. The components are
co-located in the CardButton file as named exports.
Connects #560
- Check out this branch
- Run ./scripts/beekeepers.sh start
- Add some Apiaries
- Edit their names
- Ensure you see 'Edit' and 'Save' instead of pencil and checkmark icons
- Ensure that editing still works correctly

Change button for editing apiary names

---

src/icp/apps/beekeepers/js/src/components/SurveyView.jsx

#Overview
Removed links to monthly surveys from the incompleted surveys list.
The overall survey functionality is untouched to allow for the potential
of using this functionality again in the future.
Connects #561
- Check out this branch
- Run ./scripts/beekeepers.sh start
- Add some Apiaries
- Login as a pro user
- Navigate to 'survey'
- Ensure you see only November and April surveys, and no monthly surveys

Remove links to monthly surveys

---

README.md
Vagrantfile
deployment/ansible/roles.yml

As a bit of a brute-force approach to resolving several issues with booting the virtual machines, switch to the Bento variant of a Trusty base box.
In addition:
- Upgrade the Docker Ansible role to properly set the Docker APT repository architecture
- Fix a bug with regarding some assumptions we had about access to the `ICP_SERVICES_IP` environment variable across environments
Connects https://github.com/project-icp/bee-pollinator-app/issues/563
A failed build: http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/497/
Followed by two back-to-back successful builds:
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/498/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-pull-requests/499/
Individual commit messages …

Replace ubuntu/trusty64 base box with Bento equivalent

---

deployment/ansible/group_vars/all

Something about the wheel for `psycopg2==2.7.x` loads external operating system libraries in a way that is incompatible with the versions of those libraries provided on Trusty. To avoid any issues with bundled wheel binaries, the most recent non `psycopg2-binary` package is being installed.
Seems related to https://github.com/psycopg/psycopg2-wheels/issues/2.
No reference to `psycopg2` is made in `requirements.txt` because the application expects `psycopg2` to already be there (via Ansible and the `postgresql-support` role).
I built an AMI using this branch and deployed it to staging:
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-app-and-worker/179/
- http://civicci01.internal.azavea.com/view/bees/job/bee-pollinator-staging-deployment/175/
- Ensure that the …

Fix Python libc segfault tied to psycopg2 installation

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx

Prevents users from entering a spring survey if no survey from the
previous fall exists for the apiary. If the user incorrectly begins a
a spring survey, they are prompted to complete a fall survey first,
and the survey does not render, thereby preventing them from completing
the survey.
Connects #558 
- Check out this branch
- Run ./scripts/beekeepers.sh start
- Add an Apiary
- Attempt to enter the Spring 2019 survey for the apiary. You should see an error message instead of the survey.
- Complete the Fall 2018 survey.
- You should now be able to complete the Spring 2019 survey for the apiary successfully.

No spring survey without a fall survey

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/migrations/0017_aprilsurvey_num_new_colonies.py
src/icp/apps/beekeepers/models.py
src/icp/apps/beekeepers/views.py

Adds a line that displays the number of colonies (`num_colonies`) the
user centered for that apiary in the November survey.
Adds a max value to the remaining colonies (`num_colonies`) field which
limits it to number of colonies entered in the November survey.
Adds the question - “How many new colonies did you add to this apiary
over the winter?” with a default answer of 0. This required the
addition of a field to the AprilSurvey model, `num_new_colonies`.
Existing April Surveys will have this new field marked `null`.
In the database, `num_colonies` represents the total number of colonies.
Therefore the data stored to this field is equal to the remaining
colonies plus the new colonies.
Connects #559 
* Run migrations
* Run ./scripts/beekeepers.sh start
* Add some …

Edit colony questions in April Survey

---

src/icp/apps/beekeepers/js/src/components/Map.jsx

#Overview
Previously, we were not updating the map's center when zooming. This
resulted in the map panning to the previous center after trackpad
zooms, which are intended to re-center the map at the point where the
user's cursor is when beginning the zoom. We are now correctly updating
the map's center to equal the zoom location after a zoom action ends.
Connects #555 
* Run ./scripts/beekeepers.sh start
* Zoom in and out using trackpad. Map should remain centered on the point where you zoomed in. Map should not pan after zoom.

Map correctly centers after zoom

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCardListing.jsx

Users were losing data while completing surveys, when the survey modals
would close due to the user clicking outside the modal.
The survey modals now don't close when the user clicks outside the
modal, and must instead be closed by submitting or clicking the 'x'
button.
Connects #535
This change was also applied to the monthly survey form because the monthly survey is also impacted by the change to the Popup component that prevents closing by clicking outside the box; however, the monthly surveys are currently inaccessible for testing as they aren't being used. The applicable code and functionality are identical to the November and April forms, however, so there shouldn't be any future issues.
* Run ./scripts/beekeepers.sh start
* Enter a November survey.
* Attempt …

Fixes survey modals closing unexpectedly

---

src/icp/apps/beekeepers/js/src/components/AprilSurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/js/src/utils.js
src/icp/apps/beekeepers/serializers.py
src/icp/apps/beekeepers/urls.py
src/icp/apps/beekeepers/views.py

Users are now able to edit their submitted November and April surveys.
The Survey Serializer and the RestAPI endpoints have been altered to
allow the update of surveys and sub-surveys.
The utility function getOrCreateSurvey has been split into multiple
functions (getSurvey, createSurvey, updateSurvey) to allow for the
addition of the new Survey Update functionality while maintaining
consistency in format.
The November and April Survey form fields are no longer disabled when
opening the forms for review, as users should now be able to update
them when reopening.
Parsing of multiple-choice keys has been changed slightly to handle a
bug that appeared while updating the 'Other' field.
The Monthly Survey has not been updated with edit functionality, as
Monthly Surveys are not currently in use. …

Allow users to update November and April surveys

---

src/icp/apps/beekeepers/js/src/components/GuestSurveyView.jsx

Clicking the "Participate in Study" button opened a modal that included
a link to information about wild bee hotels. That study is ending.
We have removed the sentence and link "If you have a wild bee hotel and
would like to participate in our study, please click here".
Connects #580 
* Run ./scripts/beekeepers.sh start
* Make sure you're logged out
* Navigate to 'Survey'
* You should not see the sentence "If you have a wild bee hotel and
would like to participate in our study, please click here"

Remove bee hotel survey link

---

src/icp/apps/beekeepers/js/src/constants.js

The value ranges for insecticide were recalibrated against a national
data layer. The fence-post values (0, 1000) were chosen to present
arbitrarily low and high values. The middle values of 79 and 226
represent the thresholds for low and high values, with medium
represented between the two.
Connects #589 
I had to interpret the values provided in the connected issue into the format required by the application, but this was confirmed with follow up to the client
* Test 3 and 5km values across the CONUS, and verify that the insecticide values are labeled appropriately based on this new scale. High values can be found just south of Yuba City, CA

Update insecticide reference ranges
