project-icp/bee-pollinator-app

deployment/ansible/roles.yml
src/icp/js/src/analyze/controllers.js
src/icp/js/src/core/models.js
src/icp/js/src/core/views.js
src/icp/js/src/draw/controllers.js
src/icp/js/src/draw/models.js
src/icp/js/src/draw/templates/window.html
src/icp/js/src/draw/views.js
src/icp/js/src/modeling/controllers.js
src/icp/sass/main.scss
src/icp/sass/pages/_draw.scss

Adds a sidebar in the "Draw" stage with the drawing tool.
There's an upcoming PR that gets rid of the Analyze view. With that in place, the "Confirm" button will stop crashing.
I'm putting this up quickly so other people have an idea of what I'm doing so they can start working off of this.
Pull down this branch, run the bundle script, and open [http://localhost:8000](http://localhost:8000). Ensure you are able to draw a shape, cancel drawing, and re-draw after finishing it.
Connects #22

Add Draw Sidebar

---

src/icp/js/src/analyze/controllers.js
src/icp/js/src/compare/controllers.js
src/icp/js/src/core/models.js
src/icp/js/src/core/templates/header.html
src/icp/js/src/core/tests.js
src/icp/js/src/core/views.js
src/icp/js/src/draw/controllers.js
src/icp/js/src/draw/utils.js
src/icp/js/src/main.js
src/icp/js/src/modeling/controllers.js
src/icp/js/src/projects/controllers.js
src/icp/js/src/user/templates/baseModal.html
src/icp/js/src/user/templates/loginModal.html
src/icp/sass/base/_header.scss
src/icp/sass/base/_login.scss
src/icp/sass/components/_buttons.scss
src/icp/sass/components/_inputs.scss
src/icp/sass/pages/_search-map.scss
src/icp/sass/utils/_variables.scss

- Update all the branding color variables 
- Increase the font size
- Restyle Search bar
- Restyle drawn shape masks (no border on finished shaped, brand primary while drawing)
- Remove current page title from the app header
- Don't show login modal on start 
@jfrankl -- This is more of a first pass at styling, but let me know if anything stands out for edits in the screenshots below!
- Colors eye-dropped from wireframes:
#525659 header light
#464648 header dark
#ffffff white
#a4a4a4 disabled font
#f9cf2f brand primary (the honeycomb yellow)
#58585a scenario header
#d0d0d0 active tab scenario
#b3b3b3 inactive tab scenario
#608caf active blue
More of a demonstration of the brand-primary at work, and not something that actually looks too good!
_Login modal with hover over guest …

Update Styling (Font sizes, Colors)

---

src/icp/icp/settings/base.py

Same as https://github.com/azavea/pwd-stormdrain-marking/pull/268. You know the drill.

Make dev environment accessible from internal n/w

---

src/icp/js/src/core/templates/modificationPopup.html
src/icp/js/src/draw/templates/splash.html
src/icp/js/src/draw/templates/window.html
src/icp/sass/base/_header.scss
src/icp/sass/base/_map.scss
src/icp/sass/base/_typography.scss
src/icp/sass/components/_buttons.scss
src/icp/sass/components/_dropdowns.scss
src/icp/sass/components/_inputs.scss
src/icp/sass/components/_sidebar.scss
src/icp/sass/components/_tabs.scss
src/icp/sass/pages/_compare.scss
src/icp/sass/pages/_draw.scss
src/icp/sass/pages/_model.scss
src/icp/sass/pages/_search-map.scss
src/icp/sass/utils/_variables.scss

Style cleanup

---

README.md
doc/bee_terminology.md

First commit:
- Reformatted a few heading levels to be more consistent with the rest of the Readme
- Added a section on reinstalling the model
- Added a section on receiving new data
- Added a section on updating colors
Second optional commit:
- I've been maintaining my own personal document of definitions and model relevant info. I've thrown it on here as a separate commit in case it'd be helpful to someone else jumping in on this project. Happy to remove it if it's weird to keep in the repo.

Update Readme to include CDL processing instructions

---

src/icp/js/src/core/modificationConfig.json
src/icp/js/src/core/overlayControl.js
src/icp/js/src/core/templates/layerToggleControl.html
src/icp/js/src/core/templates/overlayControl.html
src/icp/js/src/core/templates/sidebarToggleControlButton.html
src/icp/js/src/modeling/controls.js
src/icp/sass/base/_map.scss

Fixes minor visual issues. See commit messages for details.
Connects #183 
Connects #188 
Connects #200 
* Check out this branch and `./scripts/bundle.sh --debug`
* Open the app. Ensure you can enable the crop layer in a much easier way from before. Ensure that other related controls, such as the opacity slider and legend toggle, still work as before.
* Go to the modeling stage. Check the Enhancements under New Scenario. Ensure that Early variants have been removed, and Late variants have been renamed and rearranged.

Visual Fixups

---

src/icp/js/src/compare/templates/compareModifications.html
src/icp/js/src/compare/templates/compareWindow.html
src/icp/js/src/core/modificationConfig.json
src/icp/js/src/core/templates/barChart.html
src/icp/js/src/core/templates/modificationPopup.html
src/icp/js/src/draw/templates/splash.html
src/icp/js/src/draw/templates/window.html
src/icp/js/src/modeling/controllers.js
src/icp/js/src/modeling/controls.js
src/icp/js/src/modeling/modificationConfigUtils.js
src/icp/js/src/modeling/templates/controls/thumbSelect.html
src/icp/js/src/modeling/templates/controls/thumbSelectSummary.html
src/icp/js/src/modeling/templates/yieldScenarioToolbarTabContent.html
src/icp/js/src/modeling/yield/views.js
src/icp/sass/base/_base.scss
src/icp/sass/components/_dropdowns.scss
src/icp/sass/pages/_compare.scss

- The landcover mod dropdown is long and doesn't scroll: the summary at the bottom gets cut off on shorter screens 
Connects #212 
- Client had some final text changes
Connects #221 
You can see in the demo that the landcover dropdown cuts itself off prematurely — it would look better for it to take up the full available height and then add the summary region inside the container, instead of appending the summary region beneath. I was able to get the better looking behavior using flexbox, but couldn't get the flexbox implementation work in IE11 ([perhaps related to there being a nested flex element](https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview)
* Pull, bundle
* Confirm the landcover dropdown is …

Modification Thumb Select Scroll + Text Changes

---

src/icp/js/src/core/templates/sharedModificationPopup.html
src/icp/js/src/draw/templates/splash.html
src/icp/js/src/draw/templates/window.html

Text edits. See original issue for details.
Connects #230 
Shortened splash page headline:
Current Crop Map in modification popup:
Capitalized Confirm and Redraw Area:
* Check out this branch and bundle the scripts `./scripts/bundle.sh --debug`
* Ensure you see the correct edits in the correct places

Text Edits

---

src/icp/requirements/base.txt

Geocoding is now working again:
Ensure CI Tests pass.

Upgrade to Omgeo 2.0.0

---

src/icp/js/src/modeling/yield/views.js
src/icp/sass/base/_typography.scss
src/icp/sass/components/_inputs.scss
src/icp/sass/components/_tables.scss
src/icp/sass/components/_tabs.scss
src/icp/sass/pages/_model.scss
src/icp/sass/utils/_variables.scss

Style updates

---

src/icp/apps/core/templates/base.html
src/icp/js/src/compare/tours.js
src/icp/js/src/core/modificationConfig.json
src/icp/js/src/core/templates/barChart.html
src/icp/js/src/draw/templates/splash.html
src/icp/js/src/user/templates/baseModal.html

Client provided text updates throughout the app.
Connects #257 
Connects #258 
Confirm changes requested in the associated issues are represented.

Small text changes

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Map.jsx
src/icp/apps/beekeepers/js/src/constants.js
src/icp/apps/beekeepers/js/src/reducers.js
src/icp/apps/beekeepers/sass/06_components/_map.scss
src/icp/apps/beekeepers/templates/beekeepers/beekeepers.html

Add a map to the existing map component added in #312. I added a few map properties to the initial state, subject to change. It hasn't be determined what the map interactions will be yet.
Use OSM tiles for now, basemap TBD in #299 
Connects #298 
`./scripts/beekeepers.sh start` and the map should appear.

Add map to the map component

---

src/icp/apps/beekeepers/admin.py
src/icp/apps/beekeepers/migrations/0004_survey_unique_together.py
src/icp/apps/beekeepers/migrations/0005_aprilsurvey.py
src/icp/apps/beekeepers/migrations/0006_novembersurvey.py
src/icp/apps/beekeepers/migrations/0007_monthlysurvey.py
src/icp/apps/beekeepers/migrations/0008_usersurvey.py
src/icp/apps/beekeepers/models.py

Converts the [schema of subsurveys](https://docs.google.com/spreadsheets/d/1lkXvBpeyg-lhzH48CdBe_C-HuepJBaXUM2904umd7PI/) into Django models.
Connects #336 
* Run migrations
* Inspect the generated tables

Add Subsurvey Models

---

src/icp/apps/beekeepers/js/src/actions.js
src/icp/apps/beekeepers/js/src/components/Header.jsx
src/icp/apps/beekeepers/sass/02_tools/_accessibility.scss
src/icp/apps/beekeepers/sass/06_components/_navbar.scss

Implements logging out.
Connects #335 
* Go to [:8000/?beekeepers](http://localhost:8000/?beekeepers) and log in. Ensure you see a ▾ icon next to the username.
* Hover on the username. Ensure you see a dropdown with a "Log Out" button.
* Ensure hovering on the username, or the Log Out button, keeps the dropdown open and it doesn't accidentally close.
* Click the "Log Out" button. Ensure you are logged out and the app resets to its initial state.

Implement Logging Out

---

deployment/ansible/group_vars/all

To fix provisioning errors. Parallel to https://github.com/WikiWatershed/model-my-watershed/commit/ce348bc00cb1e71c33ce240eff92e611a9e1a08a
* Destroy all VMs `vagrant destroy`
* Check out this branch and provision all VMs `vagrant up`

Update Postgis to 2.2

---

src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/js/src/components/SurveyCard.jsx
src/icp/apps/beekeepers/js/src/components/SurveyView.jsx
src/icp/apps/beekeepers/sass/06_components/_survey.scss

This PR addresses the rest of the fall-out cards from the design pass and client comments before the official testing hand-off to the client.
Connects #458 
Connects #456 
Connects #455
Pull down the branch and see that everything works as expected.

Assorted clean up

---

src/icp/apps/beekeepers/js/src/components/MonthlySurveyColonyForm.jsx
src/icp/apps/beekeepers/js/src/components/MonthlySurveyForm.jsx
src/icp/apps/beekeepers/js/src/components/NovemberSurveyForm.jsx
src/icp/apps/beekeepers/migrations/0012_add_new_survey_fields.py
src/icp/apps/beekeepers/models.py

Adds a new field each to November and Monthly surveys. This includes a model change, database migration, and additions to the respective React components.
Connects #487 
I added the new fields to the very bottom of the current set of questions. For the new November Survey question "Did you treat all of the colonies in the apiary?", the default is "Yes". If these assumptions need to change, please let me know. /cc @dboyer 
* On `develop`, go to [:8000/?beekeepers](http://localhost:8000/?beekeepers), log in, and create some apiaries. Fill out a Monthly and a November survey.
* Check out this branch and `manage migrate`. Ensure migrations run successfully.
* Go back to your surveys. Ensure existing surveys have reasonable default values for the new fields.
* Fill out new surveys and ensure …

Add New Questions to Surveys

---

src/icp/apps/beekeepers/sass/06_components/_layercontrol.scss
src/icp/apps/beekeepers/sass/06_components/_map.scss
src/icp/apps/beekeepers/sass/06_components/_navbar.scss

Slightly reposition Beescape logo to be vertically centered, +/- icon sizes in zoom.
Connects #XXX
N/A
N/A

Style changes

---

deployment/MIGRATIONS.md

Updates Migrations instructions
* Attempt to enter the staging app SSH by following the directions

Update MIGRATIONS.md with icp-staging instructions

---

src/icp/apps/beekeepers/js/src/components/Map.jsx

Fixes broken Geocoding. This fix was also applied in other projects.
See: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-suggest.htm
Connects #599 
* Check out this branch and `./scripts/beekeepers.sh build`
* Go to http://localhost:8000/?beekeepers
* Try out the search bar on the map

Update Geocoder Service URL
